# 🐼 Pandas Code Lab
## Beginner Hands-On Practical Session

**Goal:** Learn Pandas by writing and running code in Jupyter Notebook.

### Topics
- Series
- DataFrame
- Inspecting data
- Selecting columns
- Filtering rows
- Adding/updating columns
- Missing values
- Basic statistics
- GroupBy
- Mini project

## 1. Setup

Run this cell first.

In [1]:
import pandas as pd

print(pd.__version__)

2.3.3

## 2. Series

A **Series** is a one-dimensional labelled data structure.

### Example

In [2]:
marks = pd.Series([80, 75, 90, 65, 88])
print(marks)

0    80
1    75
2    90
3    65
4    88
dtype: int64

### 🧪 Practice 1
Create a Series called `ages` containing:

`20, 21, 19, 22, 20`

Then print the Series and print the value at index `2`.

In [4]:
import pandas as pd

marks = pd.Series([85, 90, 78, 92, 88])

print(marks)
print("First mark:", marks[0])
print("Last mark:", marks[4])
print("Average:", marks.mean())
print("Maximum:", marks.max())
print("Minimum:", marks.min())

ModuleNotFoundError: No module named 'pandas'

## 3. Create a DataFrame

A **DataFrame** is a two-dimensional table with rows and columns.

In [4]:
data = {
    "Name": ["Arun", "Priya", "Rahul", "Divya", "Kiran"],
    "Department": ["AI", "DS", "AI", "CSE", "DS"],
    "Marks": [85, 92, 76, 88, 95],
    "Attendance": [90, 95, 75, 82, 98]
}

df = pd.DataFrame(data)
df

    Name Department  Marks  Attendance
0   Arun         AI     85          90
1  Priya         DS     92          95
2  Rahul         AI     76          75
3  Divya        CSE     88          82
4  Kiran         DS     95          98

## 4. Inspect the DataFrame

Try these commonly used commands.

In [5]:
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.dtypes)

    Name Department  Marks  Attendance
0   Arun         AI     85          90
1  Priya         DS     92          95
2  Rahul         AI     76          75
3  Divya        CSE     88          82
4  Kiran         DS     95          98
    Name Department  Marks  Attendance
0   Arun         AI     85          90
1  Priya         DS     92          95
2  Rahul         AI     76          75
3  Divya        CSE     88          82
4  Kiran         DS     95          98
(5, 4)
Index(['Name', 'Department', 'Marks', 'Attendance'], dtype='object')
Name          object
Department    object
Marks          int64
Attendance     int64
dtype: object

### 🧪 Practice 2
1. Display the first 3 rows.
2. Display the last 2 rows.
3. Find the number of rows and columns.
4. Display only the column names.

In [7]:
import pandas as pd

# Example DataFrame
data = {
    "Name": ["Arun", "Bala", "Charan", "Deepak", "Elango"],
    "Age": [20, 21, 19, 22, 20],
    "Mark": [85, 90, 78, 88, 92]
}

df = pd.DataFrame(data)

# 1. Display the first 3 rows
print(df.head(3))

# 2. Display the last 2 rows
print(df.tail(2))

# 3. Find the number of rows and columns
print(df.shape)

# 4. Display only the column names
print(df.columns)

     Name  Age  Mark
0    Arun   20    85
1    Bala   21    90
2  Charan   19    78
     Name  Age  Mark
3  Deepak   22    88
4  Elango   20    92
(5, 3)
Index(['Name', 'Age', 'Mark'], dtype='object')

## 5. Selecting Columns

### One column

In [10]:
df["Name"]

0      Arun
1      Bala
2    Charan
3    Deepak
4    Elango
Name: Name, dtype: object

### Multiple columns

In [11]:
df[["Name", "Marks"]]

KeyError: "['Marks'] not in index"

### 🧪 Practice 3
Display:
1. `Name` and `Department`
2. `Name`, `Marks`, and `Attendance`

In [12]:
# 1. Display Name and Department
print(df[["Name", "Department"]])

# 2. Display Name, Marks, and Attendance
print(df[["Name", "Marks", "Attendance"]])

KeyError: "['Department'] not in index"

## 6. Filtering Rows

Find students who scored more than 80.

In [ ]:
df[df["Marks"] > 80]

### 🧪 Practice 4
Write code to find:
1. Students with marks greater than 85.
2. Students with attendance greater than 90.
3. Students from the `AI` department.
4. Students with marks less than 80.

In [13]:
# 1. Students with marks greater than 85
print(df[df["Marks"] > 85])

# 2. Students with attendance greater than 90
print(df[df["Attendance"] > 90])

# 3. Students from the AI department
print(df[df["Department"] == "AI"])

# 4. Students with marks less than 80
print(df[df["Marks"] < 80])

KeyError: 'Marks'

## 7. Multiple Conditions

Use `&` for AND and `|` for OR.

Example: marks greater than 80 AND attendance greater than 85.

In [14]:
df[(df["Marks"] > 80) & (df["Attendance"] > 85)]

KeyError: 'Marks'

### 🧪 Practice 5
Find students who:
1. Have marks greater than 80 AND attendance greater than 90.
2. Are from AI OR DS department.

In [15]:
# 1
print(df[(df["Marks"] > 80) & (df["Attendance"] > 90)])

# 2
print(df[(df["Department"] == "AI") | (df["Department"] == "DS")])

KeyError: 'Marks'

## 8. Add and Update Columns

Create a `Pass` column.

In [17]:
df["Pass"] = df["Marks"] >= 40
df

KeyError: 'Marks'

### 🧪 Practice 6
1. Create a `Bonus` column by adding 5 marks.
2. Create a `Final_Marks` column by adding `Marks + Bonus`.
3. Create a `High_Performer` column that is `True` when marks are 85 or above.

In [18]:
df["Bonus"] = 5
df["Final_Marks"] = df["Marks"] + df["Bonus"]
df["High_Performer"] = df["Marks"] >= 85

df

KeyError: 'Marks'

## 9. Missing Values

Create a DataFrame containing a missing mark.

In [19]:
data_missing = {
    "Name": ["Arun", "Priya", "Rahul", "Divya"],
    "Marks": [85, None, 76, 90]
}

df_missing = pd.DataFrame(data_missing)
df_missing

    Name  Marks
0   Arun   85.0
1  Priya    NaN
2  Rahul   76.0
3  Divya   90.0

Useful methods:

- `isnull()` → find missing values
- `isnull().sum()` → count missing values
- `fillna()` → replace missing values

In [ ]:
print(df_missing.isnull())
print(df_missing.isnull().sum())

### 🧪 Practice 7
Fill the missing mark using the **mean of the Marks column**.

In [20]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

KeyError: 'Marks'

## 10. Basic Statistics

In [21]:
print("Mean:", df["Marks"].mean())
print("Maximum:", df["Marks"].max())
print("Minimum:", df["Marks"].min())
print("Total:", df["Marks"].sum())
print(df["Marks"].describe())

KeyError: 'Marks'

### 🧪 Practice 8
Find:
1. Average attendance
2. Highest attendance
3. Lowest attendance
4. Total marks

In [ ]:
# Write your code here

## 11. GroupBy

Find the average marks for each department.

In [ ]:
df.groupby("Department")["Marks"].mean()

### 🧪 Practice 9
1. Find the average attendance for each department.
2. Find the maximum marks for each department.
3. Count the number of students in each department.

In [22]:
print(df.groupby("Department")["Attendance"].mean())
print(df.groupby("Department")["Marks"].max())
print(df["Department"].value_counts())

KeyError: 'Department'

# 🚀 Mini Project: Student Performance Analyzer

Use the following dataset.

In [ ]:
project_data = {
    "Name": ["Arun", "Priya", "Rahul", "Divya", "Kiran", "Meena", "Vijay", "Anu"],
    "Department": ["AI", "DS", "AI", "CSE", "DS", "AI", "CSE", "DS"],
    "Marks": [85, 92, 67, 78, 95, 72, 88, 81],
    "Attendance": [90, 95, 75, 82, 98, 79, 91, 85]
}

students = pd.DataFrame(project_data)
students

## 🎯 Mini Project Tasks

Solve these independently.

1. Display the first 5 students.
2. Display only `Name` and `Marks`.
3. Find students who scored more than 80.
4. Find students with attendance greater than 85.
5. Find students with marks > 80 AND attendance > 85.
6. Find the average marks.
7. Find the highest-scoring student.
8. Find average marks for each department.
9. Add a `Performance` column: `Excellent` if marks >= 90, otherwise `Good`.
10. Find the number of students in each department.

In [ ]:
# 🚀 Write your mini-project solution here

# ✅ Final Checklist

Before finishing the lab, make sure you can write these without looking at the examples:

- [ ] Create a Series
- [ ] Create a DataFrame
- [ ] Use `head()` and `tail()`
- [ ] Use `shape`, `columns`, and `dtypes`
- [ ] Select one or multiple columns
- [ ] Filter rows
- [ ] Use `&` and `|`
- [ ] Add/update columns
- [ ] Handle missing values
- [ ] Calculate statistics
- [ ] Use `groupby()`
- [ ] Complete the mini project